# strength index via Elo

In [1]:
import os
import pandas as pd
import numpy as np

In [4]:
processed_path = os.path.join('c:\\Users\\Trainee.LAPTOP-7OL45FO7\\Desktop\\portfolio_projekt\\template_dsc', 'data', 'processed')

if os.path.exists(processed_path):
    print('True')


# get data
df_final_rankings = pd.read_csv(os.path.join(processed_path, 'Bundesliga_Rankings.csv'))
df_matches = pd.read_csv(os.path.join(processed_path, 'Bundesliga_Matches.csv'))

display(df_final_rankings.head())
display(df_matches.head())

True

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
0,1. Bundesliga,04_05,FC Bayern München,Bayern,34,77,24,5,5,75,33,42,1,100.000000
1,1. Bundesliga,04_05,FC Schalke 04,Schalke,34,63,20,11,3,56,46,10,2,94.176471
2,1. Bundesliga,04_05,Werder Bremen,Bremen,34,59,18,11,5,68,37,31,3,88.352941
3,1. Bundesliga,04_05,Hertha BSC,Hertha,34,58,15,6,13,59,31,28,4,82.529412
4,1. Bundesliga,04_05,VfB Stuttgart,Stuttgart,34,58,17,10,7,54,40,14,5,76.705882

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
0,2005-08-05 20:30:00,05_06,München,1,FC Bayern München,Borussia Mönchengladbach,3,0,0.0,1.0,0.0
1,2005-08-06 15:30:00,05_06,Köln,1,1. FC Köln,1. FSV Mainz 05,1,0,0.0,1.0,0.0
2,2005-08-06 15:30:00,05_06,Duisburg,1,MSV Duisburg,VfB Stuttgart,1,1,1.0,0.0,0.0
3,2005-08-06 15:30:00,05_06,Hamburg,1,Hamburger SV,1. FC Nürnberg,3,0,0.0,1.0,0.0
4,2005-08-06 15:30:00,05_06,Wolfsburg,1,VfL Wolfsburg,Borussia Dortmund,2,2,1.0,0.0,0.0

In [5]:
# focus on 5 comparable seasons: 09_10 to 14_15

df_rankings_5 = df_final_rankings.copy()
df_matches_5 = df_matches.copy()
dfs = [df_rankings_5, df_matches_5]

for df in dfs: 
    df = df[(df['SEASON'] == '09_10') | (df['SEASON'] == '10_11') | (df['SEASON'] == '11_12') | (df['SEASON'] == '12_13') | (df['SEASON'] == '13_14') | (df['SEASON'] == '14_15')]
    display(df.head())
    display(df.tail())

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
90,1. Bundesliga,09_10,FC Bayern München,Bayern,34,70,20,4,10,72,31,41,1,100.000000
91,1. Bundesliga,09_10,FC Schalke 04,Schalke,34,65,19,7,8,53,31,22,2,94.176471
92,1. Bundesliga,09_10,Werder Bremen,Bremen,34,61,17,7,10,71,40,31,3,88.352941
93,1. Bundesliga,09_10,Bayer Leverkusen,Leverkusen,34,59,15,5,14,65,38,27,4,82.529412
94,1. Bundesliga,09_10,Borussia Dortmund,Dortmund,34,57,16,9,9,54,42,12,5,76.705882

,League,SEASON,Team,Team_Short,Matches,Points,Won,Lost,Draw,Goals,Opponent_Goals,GoalDiff,Rank,Ratings_initial
193,1. Bundesliga,14_15,VfB Stuttgart,Stuttgart,34,36,9,16,9,42,60,-18,14,24.294118
194,1. Bundesliga,14_15,Hertha BSC,Hertha,34,35,9,17,8,36,52,-16,15,18.470588
195,1. Bundesliga,14_15,Hamburger SV,HSV,34,35,9,17,8,25,50,-25,16,12.647059
196,1. Bundesliga,14_15,SC Freiburg,Freiburg,34,34,7,14,13,36,47,-11,17,6.823529
197,1. Bundesliga,14_15,SC Paderborn 07,Paderborn,34,31,7,17,10,31,65,-34,18,1.000000

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
1224,2009-08-07 20:30:00,09_10,Wolfsburg,1,VfL Wolfsburg,VfB Stuttgart,2,0,0.0,1.0,0.0
1225,2009-08-08 15:30:00,09_10,Dortmund,1,Borussia Dortmund,1. FC Köln,1,0,0.0,1.0,0.0
1226,2009-08-08 15:30:00,09_10,Nürnberg,1,1. FC Nürnberg,FC Schalke 04,1,2,0.0,0.0,1.0
1227,2009-08-08 15:30:00,09_10,Bremen,1,Werder Bremen,Eintracht Frankfurt,2,3,0.0,0.0,1.0
1228,2009-08-08 15:30:00,09_10,Berlin,1,Hertha BSC,Hannover 96,1,0,0.0,1.0,0.0

,MATCH_DATE,SEASON,LOCATION,MATCHDAY_NR,HOME_TEAM_NAME,AWAY_TEAM_NAME,GOALS_HOME,GOALS_AWAY,DRAW,WIN_HOME,WIN_AWAY
3055,2015-05-23 15:30:00,14_15,Hannover,34,Hannover 96,SC Freiburg,2,1,0.0,1.0,0.0
3056,2015-05-23 15:30:00,14_15,Frankfurt,34,Eintracht Frankfurt,Bayer Leverkusen,2,1,0.0,1.0,0.0
3057,2015-05-23 15:30:00,14_15,Hamburg,34,Hamburger SV,FC Schalke 04,2,0,0.0,1.0,0.0
3058,2015-05-23 15:30:00,14_15,Köln,34,1. FC Köln,VfL Wolfsburg,2,2,1.0,0.0,0.0
3059,2015-05-23 15:30:00,14_15,Paderborn,34,SC Paderborn 07,VfB Stuttgart,1,2,0.0,0.0,1.0